name: build-and-push

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    uses: skccmygit/npo-platform-ci-templates/.github/workflows/docker-build-push.yml@main
    with:
      image_name: 'YOUR_APP_NAME' # TODO: (필수) 개발할 애플리케이션의 이름을 작성하세요 (예: my-app-src)
      harbor_project: 'npo'
      config_repo: 'skccmygit/YOUR_DEPLOY_REPO_NAME' # TODO: (필수) deploy 레포지토리 주소를 작성하세요 (예: skccmygit/my-app)
